/* { name: "Classic" },5
      { name: "Retro" },5
      { name: "Vintage" },5
      { name: "Urban" },5
      { name: "Feminen" },5
      { name: "Tesettür" }5 */

export const clothes = [
    {
    id: 1,
    cinsiyet: "Erkek",
    img: "https://www.yapokupayu.ru/system/ckeditor_assets/pictures/000/205/769_content.jpg",
    tarz: "Business Casual",
    ust: "Gömlek",
    alt: "Pantolon",
    ustRenk: "Beyaz",
    altRenk: "Kahve",
  },
  {
    id: 2,
    cinsiyet: "Erkek",
    img: "https://i.pinimg.com/736x/50/49/70/5049708ec17964223d2f0012d46bb170.jpg",
    tarz: "Business Casual",
    ust: "Ceket",
    alt: "Pantolon",
    ustRenk: "Lacivert",
    altRenk: "Lacivert",
  },
  {
    id: 3,
    cinsiyet: "Erkek",
    img: "https://i.pinimg.com/736x/24/c2/43/24c2432e6633bec436228722997e2faf.jpg",
    tarz: "Business Casual",
    ust: "Gömlek",
    alt: "Pantolon",
    ustRenk: "Beyaz",
    altRenk: "Yeşil",
  },
  {
    id: 4,
    cinsiyet: "Erkek",
    img: "https://cget.tango.me/contentserver/download/ZFwEpAAAvy7X6R3nhQ7-jA/TXZ04EPF",
    tarz: "Business Casual",
    ust: "Gömlek",
    alt: "Pantolon",
    ustRenk: "Mavi",
    altRenk: "Lacivert",
  },
  {
    id: 5,
    cinsiyet: "Erkek",
    img: "https://i.pinimg.com/736x/c8/ac/5e/c8ac5e3682145ee9a7fe42bcac5531dd.jpg",
    tarz: "Business Casual",
    ust: "Ceket",
    alt: "Pantolon",
    ustRenk: "Kahve",
    altRenk: "Krem",
  },
  {
    id: 6,
    cinsiyet: "Erkek",
    img: "https://i.pinimg.com/736x/81/70/4f/81704f2634cd205cbcb68ff62806cb05.jpg",
    tarz: "Retro",
    ust: "Gömlek",
    alt: "Pantolon",
    ustRenk: "Siyah",
    altRenk: "Kahve",
  },
  {
    id: 7,
    cinsiyet: "Erkek",
    img: "https://i.pinimg.com/originals/59/5c/54/595c54764e5a38c6b2cc47df4f42aaad.jpg",
    tarz: "Retro",
    ust: "Ceket",
    alt: "Pantolon",
    ustRenk: "Kırmızı",
    altRenk: "Siyah",
  },
  {
    id: 8,
    cinsiyet: "Erkek",
    img: "https://50anosdefilmes.com.br/wp-content/uploads/2019/06/zzback3.jpg",
    tarz: "Retro",
    ust: "Ceket",
    alt: "Pantolon",
    ustRenk: "Mavi",
    altRenk: "Mavi",
  },
  {
    id: 9,
    cinsiyet: "Erkek",
    img: "https://cdn.vogue.ua/i/image_720x1080/uploads/article/803/e0f/b55/00001lfwm_day2_vogueint_9jun19_credit_jonathan_daniel_pryce_236298_6155b55e0f803.jpeg.webp",
    tarz: "Retro",
    ust: "Ceket",
    alt: "Pantolon",
    ustRenk: "Kahve",
    altRenk: "Yeşil",
  },
  {
    id: 10,
    cinsiyet: "Erkek",
    img: "https://i.pinimg.com/736x/9c/32/f4/9c32f42bd4a54c24366d7687d9e22430.jpg",
    tarz: "Retro",
    ust: "Ceket",
    alt: "Pantolon",
    ustRenk: "Yeşil",
    altRenk: "Krem",
  },
  {
    id: 11,
    cinsiyet: "Erkek",
    img: "https://i.pinimg.com/originals/02/00/db/0200db230e4320552218a87a50a65665.jpg",
    tarz: "Vintage",
    ust: "Ceket",
    alt: "Pantolon",
    ustRenk: "Kahve",
    altRenk: "Mavi",
  },
  {
    id: 12,
    cinsiyet: "Erkek",
    img: "https://hotwalls.ru/wallpapers/paren_v_ochkah_i_kozhanoy_kurtke/download/720x1080.jpg",
    tarz: "Vintage",
    ust: "Ceket",
    alt: "Pantolon",
    ustRenk: "Siyah",
    altRenk: "Mavi",
  },
  {
    id: 13,
    cinsiyet: "Erkek",
    img: "https://www.suspenderstore.com/product_images/uploaded_images/vintage-nick.jpg",
    tarz: "Vintage",
    ust: "Sweatshirt",
    alt: "Pantolon",
    ustRenk: "Gri",
    altRenk: "Krem",
  },
  {
    id: 14,
    cinsiyet: "Erkek",
    img: "https://i.pinimg.com/736x/2a/8d/14/2a8d147d0fe156f43d7f44568af7d8b0.jpg",
    tarz: "Vintage",
    ust: "Ceket",
    alt: "Pantolon",
    ustRenk: "Kahve",
    altRenk: "Beyaz",
  },
  {
    id: 15,
    cinsiyet: "Erkek",
    img: "https://sun9-55.userapi.com/c855224/v855224612/1a7a4a/nbGfGami2Aw.jpg",
    tarz: "Vintage",
    ust: "Ceket",
    alt: "Pantolon",
    ustRenk: "Mor",
    altRenk: "Mor",
  },
  //BASİC
  {
    id: 16,
    cinsiyet: "Erkek",
    img: "https://i.pinimg.com/736x/9d/27/9e/9d279ee2353306961ca763b4b3e1e027.jpg",
    tarz: "Basic",
    ust: "Tişört",
    alt: "Pantolon",
    ustRenk: "Beyaz",
    altRenk: "Mavi",
  },
  {
    id: 17,
    cinsiyet: "Erkek",
    img: "https://cdn.vogue.ua/i/image_720x/upload/New%20York%20str%20RS15%202932.jpg.webp",
    tarz: "Basic",
    ust: "Sweatshirt",
    alt: "Pantolon",
    ustRenk: "Gri",
    altRenk: "Kahve",
  },
  {
    id: 18,
    cinsiyet: "Erkek",
    img: "https://st4.styapokupayu.ru/images/blog_post_images/000/151/057_original.jpg",
    tarz: "Basic",
    ust: "Tişört",
    alt: "Şort",
    ustRenk: "Yeşil",
    altRenk: "Kahve",
  },
  {
    id: 19,
    cinsiyet: "Erkek",
    img: "https://www.yapokupayu.ru/system/ckeditor_assets/pictures/000/205/770_content.jpg",
    tarz: "Basic",
    ust: "Gömlek",
    alt: "Şort",
    ustRenk: "Beyaz",
    altRenk: "Siyah",
  },
  {
    id: 20,
    cinsiyet: "Erkek",
    img: "https://sc04.alicdn.com/kf/Hab9f069ea9474008992062f2cd01ec47W/238754223/Hab9f069ea9474008992062f2cd01ec47W.jpg",
    tarz: "Basic",
    ust: "Gömlek",
    alt: "Pantolon",
    ustRenk: "Beyaz",
    altRenk: "Siyah",
  },
  //OLD MONEY
  {
    id: 21,
    cinsiyet: "Erkek",
    img: "https://i.pinimg.com/originals/90/d8/12/90d812764f814738ffcc200701313dc5.jpg",
    tarz: "Old Money",
    ust: "Ceket",
    alt: "Pantolon",
    ustRenk: "Kahve",
    altRenk: "Beyaz",
  },
  {
    id: 22,
    cinsiyet: "Erkek",
    img: "https://modof.club/uploads/posts/2021-12/1638819211_21-modof-club-p-muzhskie-obrazi-so-shlyapoi-foto-21.jpg",
    tarz: "Old Money",
    ust: "Ceket",
    alt: "Pantolon",
    ustRenk: "Gri",
    altRenk: "Siyah",
  },
  {
    id: 23,
    cinsiyet: "Erkek",
    img: "https://sun9-12.userapi.com/c633417/v633417679/23130/vZ1oFVWx7yI.jpg",
    tarz: "Old Money",
    ust: "Ceket",
    alt: "Pantolon",
    ustRenk: "Kahve",
    altRenk: "Gri",
  },  
  {
    id: 24,
    cinsiyet: "Erkek",
    img: "https://www.yapokupayu.ru/system/ckeditor_assets/pictures/000/205/764_content.jpg",
    tarz: "Old Money",
    ust: "Ceket",
    alt: "Pantolon",
    ustRenk: "Krem",
    altRenk: "Beyaz",
  },  
  {
    id: 25,
    cinsiyet: "Erkek",
    img: "https://tdsm63.ru/wp-content/uploads/ddd-22.jpg",
    tarz: "Old Money",
    ust: "Ceket",
    alt: "Pantolon",
    ustRenk: "Gri",
    altRenk: "Siyah",
  },  
  //STREET
  {
    id: 26,
    cinsiyet: "Erkek",
    img: "https://i.pinimg.com/736x/7b/c5/14/7bc514eb27092746da731511584bbd3e.jpg",
    tarz: "Street",
    ust: "Gömlek",
    alt: "Pantolon",
    ustRenk: "Gri",
    altRenk: "Siyah",
  }, 
  {
    id: 27,
    cinsiyet: "Erkek",
    img: "https://static.ticimax.cloud/cdn-cgi/image/width=720,quality=99/40038/uploads/urunresimleri/buyuk/paralel-orgulu-detayli-oversize-kazak--1-bf4a.jpg",
    tarz: "Street",
    ust: "Sweatshirt",
    alt: "Pantolon",
    ustRenk: "Beyaz",
    altRenk: "Beyaz",
  }, 
  {
    id: 28,
    cinsiyet: "Erkek",
    img: "https://s1.r29static.com/bin/entry/120/720x1080,85/1011158/image.webp",
    tarz: "Street",
    ust: "Ceket",
    alt: "Pantolon",
    ustRenk: "Yeşil",
    altRenk: "Lacivert",
  }, 
  {
    id: 29,
    cinsiyet: "Erkek",
    img: "https://i.pinimg.com/736x/0e/a0/3f/0ea03ff9c321ca34b55657a8c3b73823.jpg",
    tarz: "Street",
    ust: "Ceket",
    alt: "Pantolon",
    ustRenk: "Kırmızı",
    altRenk: "Mavi",
  }, 
  {
    id: 30,
    cinsiyet: "Erkek",
    img: "https://media.gq.com/photos/577e9f92e2724dae2eb43aea/master/w_320%2Cc_limit/kanye-all-white-2.jpg",
    tarz: "Street",
    ust: "Sweatshirt",
    alt: "Pantolon",
    ustRenk: "Beyaz",
    altRenk: "Beyaz",
  },
  {
    id: 31,
    cinsiyet: "Kadin",
    img: "https://i.pinimg.com/736x/26/c1/35/26c1357d5d13e719298b687284d92188.jpg",
    tarz: "Classic",
    ust: "Bluz",
    alt: "Etek",
    ustRenk: "Krem",
    altRenk: "Kahve",
  },
  {
    id: 32,
    cinsiyet: "Kadin",
    img: "https://i.pinimg.com/736x/81/bf/59/81bf595f27b565f293f1d1ce4cce2572.jpg",
    tarz: "Classic",
    ust: "Tişört",
    alt: "Pantolon",
    ustRenk: "Beyaz",
    altRenk: "Mavi",
  },
  {
    id: 33,
    cinsiyet: "Kadin",
    img: "https://i.pinimg.com/originals/ee/72/04/ee7204345462ee958b700bf65edb907b.jpg",
    tarz: "Classic",
    ust: "Elbise",
    alt: "alt",
    ustRenk: "Yeşil",
    altRenk: "Yeşil",
  },
  {
    id: 34,
    cinsiyet: "Kadin",
    img: "https://www.colady.ru/wp-content/uploads/2021/02/obraz-2.jpg",
    tarz: "Classic",
    ust: "Sweatshirt",
    alt: "Etek",
    ustRenk: "Siyah",
    altRenk: "Siyah",
  },
  {
    id: 35,
    cinsiyet: "Kadin",
    img: "https://i.pinimg.com/736x/9c/69/20/9c6920e8120e857ace5a2524b794b1f0.jpg",
    tarz: "Classic",
    ust: "Sweatshirt",
    alt: "Pantolon",
    ustRenk: "Beyaz",
    altRenk: "Krem",
  },
  {
    id: 36,
    cinsiyet: "Kadin",
    img: "https://i.pinimg.com/736x/a9/cf/13/a9cf13b0ed585688bc123db4e7f71698.jpg",
    tarz: "Retro",
    ust: "Gömlek",
    alt: "Etek",
    ustRenk: "Beyaz",
    altRenk: "Siyah",
  },
  {
    id: 37,
    cinsiyet: "Kadin",
    img: "https://i.pinimg.com/originals/97/56/9d/97569d88436f0657d7ee13c11280d51c.jpg",
    tarz: "Retro",
    ust: "Gömlek",
    alt: "Etek",
    ustRenk: "Mavi",
    altRenk: "Pembe",
  },
  {
    id: 38,
    cinsiyet: "Kadin",
    img: "https://i.pinimg.com/originals/e8/e2/74/e8e274ed2f566aefef6028afc35ac9b2.jpg",
    tarz: "Retro",
    ust: "Bluz",
    alt: "Etek",
    ustRenk: "Siyah",
    altRenk: "Kahve",
  },
  {
    id: 39,
    cinsiyet: "Kadin",
    img: "https://i.pinimg.com/originals/4a/e7/5c/4ae75c561c1fc30ec8131d59228c659c.jpg",
    tarz: "Retro",
    ust: "Elbise",
    alt: "alt",
    ustRenk: "Gri",
    altRenk: "Gri",
  },
  {
    id: 40,
    cinsiyet: "Kadin",
    img: "https://koroleva.vip/wp-content/uploads/2023/04/1-4-1.jpg",
    tarz: "Retro",
    ust: "Elbise",
    alt: "alt",
    ustRenk: "Beyaz",
    altRenk: "Beyaz",
  },
  {
    id: 41,
    cinsiyet: "Kadin",
    img: "https://i.pinimg.com/736x/34/74/54/347454ca66c82985be98cdf974a736ef.jpg",
    tarz: "Urban",
    ust: "Tişört",
    alt: "Etek",
    ustRenk: "Beyaz",
    altRenk: "Siyah",
  },
  {
    id: 42,
    cinsiyet: "Kadin",
    img: "https://blog.oscarcalcados.com.br/wp-content/uploads/2022/10/shorts-jeans-inverno-edited.png",
    tarz: "Urban",
    ust: "Ceket",
    alt: "Şort",
    ustRenk: "Siyah",
    altRenk: "Mavi",
  },
  {
    id: 43,
    cinsiyet: "Kadin",
    img: "https://i.pinimg.com/736x/aa/25/94/aa25947452284b93f3ddc06c3a4e6b1e--backpacking-beverly-hills.jpg",
    tarz: "Urban",
    ust: "Ceket",
    alt: "Pantolon",
    ustRenk: "Gri",
    altRenk: "Mavi",
  },
  {
    id: 44,
    cinsiyet: "Kadin",
    img: "https://i.pinimg.com/736x/85/a1/0e/85a10e1efa8e6858ddd7ec9fae4be0d7.jpg",
    tarz: "Urban",
    ust: "Ceket",
    alt: "Eşofman",
    ustRenk: "Mavi",
    altRenk: "Siyah",
  },
  {
    id: 45,
    cinsiyet: "Kadin",
    img: "https://areademulher.r7.com/wp-content/uploads/2020/01/looks-com-tenis-opcoes-de-looks-com-todos-os-estilos-de-tenis-41.jpg",
    tarz: "Urban",
    ust: "Gömlek",
    alt: "Pantolon",
    ustRenk: "Mavi",
    altRenk: "Beyaz",
  },
  {
    id: 46,
    cinsiyet: "Kadin",
    img: "https://avatars.mds.yandex.net/i?id=141106435517d3d555a286b26f60e48b-4080060-images-thumbs&n=13",
    tarz: "Feminen",
    ust: "Tişört",
    alt: "Etek",
    ustRenk: "Beyaz",
    altRenk: "Pembe",
  },
  {
    id: 47,
    cinsiyet: "Kadin",
    img: "https://www.yapokupayu.ru/system/ckeditor_assets/pictures/000/190/924_content.jpg",
    tarz: "Feminen",
    ust: "Bluz",
    alt: "Etek",
    ustRenk: "Krem",
    altRenk: "Siyah",
  },
  {
    id: 48,
    cinsiyet: "Kadin",
    img: "https://i.tmgrup.com.tr/vogue/original/15-06/07/picture_1080p-21099.jpg",
    tarz: "Feminen",
    ust: "Elbise",
    alt: "alt",
    ustRenk: "Pembe",
    altRenk: "Pembe",
  },
  {
    id: 49,
    cinsiyet: "Kadin",
    img: "https://i.tmgrup.com.tr/vogue/original/15-06/07/picture_1080p-306598.jpg",
    tarz: "Feminen",
    ust: "Elbise",
    alt: "alt",
    ustRenk: "Krem",
    altRenk: "Krem",
  },
  {
    id: 50,
    cinsiyet: "Kadin",
    img: "https://img.huffingtonpost.com/asset/57ebb5731700004007ac7c3a.jpeg?ops=scalefit_720_noupscale",
    tarz: "Feminen",
    ust: "Elbise",
    alt: "alt",
    ustRenk: "Pembe",
    altRenk: "Pembe",
  },
  {
    id: 51,
    cinsiyet: "Kadin",
    img: "https://avatars.mds.yandex.net/i?id=0baf539a1a13cf8665221af0631121458107a28e-8451085-images-thumbs&n=13",
    tarz: "Tesettür",
    ust: "Elbise",
    alt: "alt",
    ustRenk: "Pembe",
    altRenk: "Pembe",
  },
  {
    id: 52,
    cinsiyet: "Kadin",
    img: "http://www.gokyuzugunlugu.com/wp-content/uploads/2015/07/hakim-3.jpg",
    tarz: "Tesettür",
    ust: "Ceket",
    alt: "Pantolon",
    ustRenk: "Kırmızı",
    altRenk: "Siyah",
  },
  {
    id: 53,
    cinsiyet: "Kadin",
    img: "https://i.pinimg.com/736x/57/0c/0c/570c0ceba2e57ead550bfde0d611c708.jpg",
    tarz: "Tesettür",
    ust: "Elbise",
    alt: "alt",
    ustRenk: "Pembe",
    altRenk: "Pembe",
  },
  {
    id: 54,
    cinsiyet: "Kadin",
    img: "https://avatars.mds.yandex.net/i?id=2248a98dc7d36709e4550539fe00add897c80a19-8175992-images-thumbs&n=13",
    tarz: "Tesettür",
    ust: "Elbise",
    alt: "alt",
    ustRenk: "Yeşil",
    altRenk: "Yeşil",
  },
  {
    id: 55,
    cinsiyet: "Kadin",
    img: "https://i.pinimg.com/originals/1f/cb/57/1fcb57b0aa45c30006ce54c51aede4ef.jpg",
    tarz: "Tesettür",
    ust: "Gömlek",
    alt: "Etek",
    ustRenk: "Beyaz",
    altRenk: "Kahve",
  },
  {
    id: 56,
    cinsiyet: "Kadin",
    img: "https://st25.styapokupayu.ru/images/blog_post_images/000/284/573_original.jpg",
    tarz: "Vintage",
    ust: "Elbise",
    alt: "alt",
    ustRenk: "Kahve",
    altRenk: "Kahve",
  },
  {
    id: 57,
    cinsiyet: "Kadin",
    img: "https://sun9-68.userapi.com/impg/OKtrOlo4YroSyTOMoEzV3qPxs7p4rngjzygv7A/3Ujk_t_-4cM.jpg?size=720x1080&quality=95&sign=c5caa4fefbadc77fb3b0bbdc1fc23129&c_uniq_tag=D5_12M5mDZqK1-IscdvtrTt_UY0_SthVQIIMacx8PJs&type=album",
    tarz: "Vintage",
    ust: "Crop",
    alt: "Pantolon",
    ustRenk: "Siyah",
    altRenk: "Mavi",
  },
  {
    id: 58,
    cinsiyet: "Kadin",
    img: "https://i.pinimg.com/736x/27/ea/44/27ea44312302a991091b8289bff3472d--vintage-trends-vintage-girls.jpg",
    tarz: "Vintage",
    ust: "Gömlek",
    alt: "Etek",
    ustRenk: "Beyaz",
    altRenk: "Mavi",
  },
  {
    id: 59,
    cinsiyet: "Kadin",
    img: "https://i.pinimg.com/736x/c5/3e/5a/c53e5a397061cf37b59f3d5dec9e2bcc.jpg",
    tarz: "Vintage",
    ust: "Ceket",
    alt: "Pantolon",
    ustRenk: "Siyah",
    altRenk: "Kahve",
  },
  {
    id: 60,
    cinsiyet: "Kadin",
    img: "https://i.pinimg.com/736x/8c/5f/b7/8c5fb7767c0bac1fc530b4cc31fb4517.jpg",
    tarz: "Vintage",
    ust: "Gömlek",
    alt: "Etek",
    ustRenk: "Kahve",
    altRenk: "Kahve",
  },
];
export default clothes
